### ISSUE TITLE
Product content

### ISSUE THREAD

**Issue by arthurvanl** [team-bicep/bol-retailer-api#1]
Hi!

I was wondering if you tried using the product content API.

Im interested for the following features:
- I want to add categories to a (new or existing) product
- I want to update the attributes that are added to an ean.

**Comment by oga-sven** [comment]
Thanks for your post. Up until now ive only added an endpoint when had a requirement for it. ill take a look at the product content endpoints now that theres interest in it :)

**Comment by oga-sven** [comment]
but please keep in mind hat i am only making a usable mirror of the existing api documentations for ease of usage. outside of special cases like the export method, i dont plan on adding custom implemenation. 
https://api.bol.com/retailer/public/redoc/v10/retailer.html#tag/Product-Content/
however i believe both of the things you mentioned are possible through the `POST https://api.bol.com/retailer/content/products` method
